// FoodFootprint - Food Database & Estimation Engine

export interface FoodResource {
  water: number;       // liters
  carbon: number;      // kg CO2e
  land: number;        // m²
  energy: number;      // kWh
  packaging: number;   // grams
}

export interface Ingredient {
  name: string;
  portion: string;
  water: number;
  carbon: number;
  land: number;
  energy: number;
  icon: string;
  color: string;
  note?: string;
}

export interface FoodItem {
  id: string;
  name: string;
  category: string;
  emoji: string;
  servingSize: string;
  servingGrams: number;
  resources: FoodResource;
  ingredients: Ingredient[];
  confidenceScore: number;
  impactLevel: 'low' | 'medium' | 'high';
  funFacts: string[];
  waterComparison: string;
  carbonComparison: string;
  tags: string[];
}

export const FOOD_DATABASE: Record<string, FoodItem> = {
  pizza: {
    id: 'pizza',
    name: 'Margherita Pizza',
    category: 'Baked Goods',
    emoji: '🍕',
    servingSize: '2 slices (250g)',
    servingGrams: 250,
    resources: {
      water: 1260,
      carbon: 1.6,
      land: 2.8,
      energy: 1.4,
      packaging: 180,
    },
    impactLevel: 'medium',
    confidenceScore: 0.91,
    funFacts: [
      'The cheese alone accounts for 65% of the water footprint',
      'It takes about 125 liters of water to produce just 100g of mozzarella',
      'The wheat for pizza dough requires around 130 liters of water per 100g',
    ],
    waterComparison: '63 drinking glasses',
    carbonComparison: '6.4 km of car driving',
    tags: ['cheese', 'wheat', 'dairy'],
    ingredients: [
      {
        name: 'Mozzarella Cheese',
        portion: '80g',
        water: 820,
        carbon: 0.9,
        land: 1.6,
        energy: 0.6,
        icon: '🧀',
        color: '#F59E0B',
        note: 'Dairy is the biggest water user in pizza',
      },
      {
        name: 'Wheat Dough',
        portion: '120g',
        water: 195,
        carbon: 0.3,
        land: 0.7,
        energy: 0.4,
        icon: '🌾',
        color: '#D97706',
      },
      {
        name: 'Tomato Sauce',
        portion: '40g',
        water: 48,
        carbon: 0.05,
        land: 0.2,
        energy: 0.1,
        icon: '🍅',
        color: '#EF4444',
      },
      {
        name: 'Olive Oil',
        portion: '10g',
        water: 145,
        carbon: 0.02,
        land: 0.1,
        energy: 0.05,
        icon: '🫒',
        color: '#22C55E',
      },
      {
        name: 'Cooking Energy',
        portion: 'oven bake',
        water: 0,
        carbon: 0.2,
        land: 0,
        energy: 0.25,
        icon: '🔥',
        color: '#EF4444',
        note: 'Gas or electric oven at 240°C for 12 min',
      },
      {
        name: 'Cardboard Box',
        portion: '180g packaging',
        water: 52,
        carbon: 0.13,
        land: 0.2,
        energy: 0.0,
        icon: '📦',
        color: '#A78BFA',
        note: 'Corrugated cardboard, transport included',
      },
    ],
  },

  burger: {
    id: 'burger',
    name: 'Beef Burger',
    category: 'Fast Food',
    emoji: '🍔',
    servingSize: '1 burger (200g)',
    servingGrams: 200,
    resources: {
      water: 2500,
      carbon: 3.1,
      land: 6.7,
      energy: 2.2,
      packaging: 85,
    },
    impactLevel: 'high',
    confidenceScore: 0.94,
    funFacts: [
      'A beef burger uses more water than a 1-hour shower',
      'Beef produces 20x more CO2 than tofu per gram of protein',
      'The land used could grow 8 salads',
    ],
    waterComparison: '125 drinking glasses',
    carbonComparison: '12.4 km of car driving',
    tags: ['beef', 'meat', 'high-impact'],
    ingredients: [
      {
        name: 'Beef Patty',
        portion: '120g',
        water: 1848,
        carbon: 2.6,
        land: 5.5,
        energy: 1.4,
        icon: '🥩',
        color: '#EF4444',
        note: 'Beef is one of the most resource-intensive proteins',
      },
      {
        name: 'Sesame Bun',
        portion: '50g',
        water: 70,
        carbon: 0.12,
        land: 0.5,
        energy: 0.2,
        icon: '🍞',
        color: '#D97706',
      },
      {
        name: 'Cheddar Cheese',
        portion: '20g',
        water: 410,
        carbon: 0.2,
        land: 0.4,
        energy: 0.3,
        icon: '🧀',
        color: '#F59E0B',
      },
      {
        name: 'Lettuce & Tomato',
        portion: '30g',
        water: 30,
        carbon: 0.02,
        land: 0.15,
        energy: 0.05,
        icon: '🥬',
        color: '#22C55E',
      },
      {
        name: 'Condiments',
        portion: '20g',
        water: 22,
        carbon: 0.03,
        land: 0.1,
        energy: 0.02,
        icon: '🥫',
        color: '#F59E0B',
      },
      {
        name: 'Wrapper & Box',
        portion: '85g',
        water: 120,
        carbon: 0.13,
        land: 0.05,
        energy: 0.23,
        icon: '📦',
        color: '#A78BFA',
      },
    ],
  },

  apple: {
    id: 'apple',
    name: 'Fresh Apple',
    category: 'Fruit',
    emoji: '🍎',
    servingSize: '1 medium apple (182g)',
    servingGrams: 182,
    resources: {
      water: 125,
      carbon: 0.09,
      land: 0.4,
      energy: 0.15,
      packaging: 5,
    },
    impactLevel: 'low',
    confidenceScore: 0.97,
    funFacts: [
      'Apples are one of the most water-efficient fruits',
      'Local apples have 90% lower transport emissions',
      'An apple tree sequesters about 21 kg of CO2 per year',
    ],
    waterComparison: '6 drinking glasses',
    carbonComparison: '0.36 km of car driving',
    tags: ['fruit', 'local', 'low-impact'],
    ingredients: [
      {
        name: 'Apple (Irrigation)',
        portion: '182g',
        water: 110,
        carbon: 0.05,
        land: 0.35,
        energy: 0.08,
        icon: '🍎',
        color: '#22C55E',
        note: 'Includes orchard water and irrigation',
      },
      {
        name: 'Pesticides & Fertiliser',
        portion: 'production',
        water: 8,
        carbon: 0.02,
        land: 0,
        energy: 0.05,
        icon: '🌱',
        color: '#4ADE80',
      },
      {
        name: 'Transport',
        portion: 'average 200km',
        water: 7,
        carbon: 0.02,
        land: 0.05,
        energy: 0.02,
        icon: '🚚',
        color: '#6B7280',
      },
    ],
  },

  coffee: {
    id: 'coffee',
    name: 'Black Coffee',
    category: 'Beverages',
    emoji: '☕',
    servingSize: '1 cup (250ml)',
    servingGrams: 250,
    resources: {
      water: 140,
      carbon: 0.21,
      land: 0.3,
      energy: 0.3,
      packaging: 10,
    },
    impactLevel: 'low',
    confidenceScore: 0.95,
    funFacts: [
      'It takes 140 liters of water to grow the beans for one cup',
      'Coffee production supports 125 million people worldwide',
      'Shade-grown coffee uses 60% less water',
    ],
    waterComparison: '7 drinking glasses',
    carbonComparison: '0.84 km of car driving',
    tags: ['beverage', 'caffeine', 'tropical'],
    ingredients: [
      {
        name: 'Coffee Beans',
        portion: '7g',
        water: 130,
        carbon: 0.15,
        land: 0.28,
        energy: 0.1,
        icon: '☕',
        color: '#D97706',
        note: 'Bean cultivation is 94% of total water footprint',
      },
      {
        name: 'Brewing Energy',
        portion: 'espresso machine',
        water: 0,
        carbon: 0.05,
        land: 0,
        energy: 0.18,
        icon: '⚡',
        color: '#F59E0B',
      },
      {
        name: 'Disposal & Cup',
        portion: 'paper cup',
        water: 10,
        carbon: 0.01,
        land: 0.02,
        energy: 0.02,
        icon: '🥤',
        color: '#A78BFA',
      },
    ],
  },

  salad: {
    id: 'salad',
    name: 'Garden Salad',
    category: 'Vegetables',
    emoji: '🥗',
    servingSize: '1 bowl (200g)',
    servingGrams: 200,
    resources: {
      water: 62,
      carbon: 0.06,
      land: 0.35,
      energy: 0.08,
      packaging: 20,
    },
    impactLevel: 'low',
    confidenceScore: 0.88,
    funFacts: [
      'Salad is one of the lowest impact meals you can eat',
      'Choosing local, seasonal greens cuts transport emissions by 80%',
      'Avoiding meat saves 50x more water than skipping a shower',
    ],
    waterComparison: '3 drinking glasses',
    carbonComparison: '0.24 km of car driving',
    tags: ['vegan', 'low-impact', 'healthy'],
    ingredients: [
      {
        name: 'Lettuce Mix',
        portion: '100g',
        water: 15,
        carbon: 0.01,
        land: 0.12,
        energy: 0.02,
        icon: '🥬',
        color: '#22C55E',
      },
      {
        name: 'Tomatoes',
        portion: '60g',
        water: 22,
        carbon: 0.02,
        land: 0.1,
        energy: 0.02,
        icon: '🍅',
        color: '#EF4444',
      },
      {
        name: 'Cucumber & Onion',
        portion: '40g',
        water: 18,
        carbon: 0.01,
        land: 0.08,
        energy: 0.01,
        icon: '🥒',
        color: '#4ADE80',
      },
      {
        name: 'Olive Oil Dressing',
        portion: '10g',
        water: 7,
        carbon: 0.02,
        land: 0.05,
        energy: 0.01,
        icon: '🫒',
        color: '#F59E0B',
      },
    ],
  },

  steak: {
    id: 'steak',
    name: 'Beef Steak',
    category: 'Meat',
    emoji: '🥩',
    servingSize: '1 serving (225g)',
    servingGrams: 225,
    resources: {
      water: 3465,
      carbon: 5.4,
      land: 10.2,
      energy: 3.1,
      packaging: 30,
    },
    impactLevel: 'high',
    confidenceScore: 0.96,
    funFacts: [
      'A single steak uses more water than 50 days of drinking water',
      'Beef uses 160x more land than potatoes per calorie',
      'Replacing one steak a week saves 330 kg CO2 per year',
    ],
    waterComparison: '173 drinking glasses',
    carbonComparison: '21.6 km of car driving',
    tags: ['beef', 'meat', 'very-high-impact'],
    ingredients: [
      {
        name: 'Beef (Grass-fed)',
        portion: '225g',
        water: 3200,
        carbon: 4.7,
        land: 9.5,
        energy: 2.5,
        icon: '🥩',
        color: '#EF4444',
        note: 'Beef cattle are methane producers — 296x more potent than CO2',
      },
      {
        name: 'Feed & Pasture',
        portion: 'included',
        water: 200,
        carbon: 0.5,
        land: 0.6,
        energy: 0.4,
        icon: '🌾',
        color: '#D97706',
      },
      {
        name: 'Cooking Energy',
        portion: 'grill/pan',
        water: 0,
        carbon: 0.15,
        land: 0,
        energy: 0.18,
        icon: '🔥',
        color: '#F59E0B',
      },
      {
        name: 'Packaging',
        portion: '30g',
        water: 65,
        carbon: 0.05,
        land: 0.1,
        energy: 0.02,
        icon: '📦',
        color: '#A78BFA',
      },
    ],
  },

  banana: {
    id: 'banana',
    name: 'Banana',
    category: 'Fruit',
    emoji: '🍌',
    servingSize: '1 banana (120g)',
    servingGrams: 120,
    resources: {
      water: 160,
      carbon: 0.086,
      land: 0.3,
      energy: 0.12,
      packaging: 0,
    },
    impactLevel: 'low',
    confidenceScore: 0.98,
    funFacts: [
      'Bananas naturally biodegrade and return nutrients to soil',
      'The peel can be composted to reduce methane in landfill',
      'Bananas are one of the best value-per-calorie foods environmentally',
    ],
    waterComparison: '8 drinking glasses',
    carbonComparison: '0.34 km of car driving',
    tags: ['fruit', 'tropical', 'low-impact'],
    ingredients: [
      {
        name: 'Banana (Crop)',
        portion: '120g',
        water: 135,
        carbon: 0.05,
        land: 0.25,
        energy: 0.08,
        icon: '🍌',
        color: '#F59E0B',
      },
      {
        name: 'Transport (Ship)',
        portion: 'avg. 8000km',
        water: 25,
        carbon: 0.036,
        land: 0.05,
        energy: 0.04,
        icon: '🚢',
        color: '#3B82F6',
        note: 'Ships are 50x more efficient than planes per tonne',
      },
    ],
  },

  chicken: {
    id: 'chicken',
    name: 'Grilled Chicken',
    category: 'Meat',
    emoji: '🍗',
    servingSize: '1 breast (165g)',
    servingGrams: 165,
    resources: {
      water: 560,
      carbon: 0.86,
      land: 1.8,
      energy: 0.9,
      packaging: 25,
    },
    impactLevel: 'medium',
    confidenceScore: 0.93,
    funFacts: [
      'Chicken has 6x lower carbon footprint than beef per gram',
      'Poultry farming uses 86% less water than beef cattle',
      'Choosing chicken over beef for 1 year saves 1,500 kg CO2',
    ],
    waterComparison: '28 drinking glasses',
    carbonComparison: '3.44 km of car driving',
    tags: ['poultry', 'protein', 'medium-impact'],
    ingredients: [
      {
        name: 'Chicken Breast',
        portion: '165g',
        water: 450,
        carbon: 0.62,
        land: 1.5,
        energy: 0.6,
        icon: '🍗',
        color: '#F59E0B',
      },
      {
        name: 'Feed (Soy/Grain)',
        portion: 'included',
        water: 90,
        carbon: 0.18,
        land: 0.25,
        energy: 0.2,
        icon: '🌽',
        color: '#D97706',
      },
      {
        name: 'Cooking',
        portion: 'grill',
        water: 0,
        carbon: 0.05,
        land: 0,
        energy: 0.08,
        icon: '🔥',
        color: '#EF4444',
      },
      {
        name: 'Packaging',
        portion: '25g',
        water: 20,
        carbon: 0.01,
        land: 0.05,
        energy: 0.02,
        icon: '📦',
        color: '#A78BFA',
      },
    ],
  },

  pasta: {
    id: 'pasta',
    name: 'Pasta (Tomato Sauce)',
    category: 'Grain',
    emoji: '🍝',
    servingSize: '1 serving (320g cooked)',
    servingGrams: 320,
    resources: {
      water: 280,
      carbon: 0.48,
      land: 0.9,
      energy: 0.6,
      packaging: 40,
    },
    impactLevel: 'low',
    confidenceScore: 0.9,
    funFacts: [
      'Pasta is one of the most water-efficient ways to get carbs',
      'Cooking pasta in the right amount of water saves 30% energy',
      'Whole wheat pasta has 40% more nutrients per water liter',
    ],
    waterComparison: '14 drinking glasses',
    carbonComparison: '1.92 km of car driving',
    tags: ['grain', 'vegetarian', 'low-impact'],
    ingredients: [
      {
        name: 'Durum Wheat Pasta',
        portion: '80g dry',
        water: 190,
        carbon: 0.22,
        land: 0.6,
        energy: 0.25,
        icon: '🍝',
        color: '#F59E0B',
      },
      {
        name: 'Tomato Sauce',
        portion: '150g',
        water: 55,
        carbon: 0.08,
        land: 0.2,
        energy: 0.12,
        icon: '🍅',
        color: '#EF4444',
      },
      {
        name: 'Parmesan Cheese',
        portion: '20g',
        water: 28,
        carbon: 0.12,
        land: 0.08,
        energy: 0.18,
        icon: '🧀',
        color: '#D97706',
        note: 'Even small amounts of cheese add significant impact',
      },
      {
        name: 'Cooking Energy',
        portion: 'boiling + sauce',
        water: 7,
        carbon: 0.06,
        land: 0,
        energy: 0.05,
        icon: '⚡',
        color: '#F59E0B',
      },
    ],
  },
};

// Categories for unknown food estimation
export const CATEGORY_ESTIMATES: Record<string, Partial<FoodResource>> = {
  'Beef/Lamb': { water: 15000, carbon: 27, land: 164, energy: 20 },
  'Pork': { water: 5990, carbon: 12, land: 11, energy: 10 },
  'Poultry': { water: 4330, carbon: 6.9, land: 7.1, energy: 5 },
  'Fish (farmed)': { water: 3691, carbon: 13.6, land: 3.7, energy: 8 },
  'Dairy': { water: 1020, carbon: 3.2, land: 8.9, energy: 4 },
  'Eggs': { water: 196, carbon: 4.8, land: 5.7, energy: 3 },
  'Legumes': { water: 1230, carbon: 0.9, land: 3.4, energy: 1 },
  'Nuts': { water: 1387, carbon: 0.4, land: 43.0, energy: 2 },
  'Grains': { water: 1644, carbon: 1.6, land: 3.3, energy: 1.5 },
  'Vegetables': { water: 322, carbon: 0.5, land: 0.8, energy: 0.4 },
  'Fruit': { water: 962, carbon: 0.4, land: 0.5, energy: 0.3 },
  'Mixed Dish': { water: 1200, carbon: 2.0, land: 3.0, energy: 2.0 },
};

// Keyword-to-food mapping for text recognition
export const KEYWORD_MAP: Record<string, string> = {
  pizza: 'pizza',
  burger: 'burger',
  hamburger: 'burger',
  cheeseburger: 'burger',
  apple: 'apple',
  coffee: 'coffee',
  espresso: 'coffee',
  latte: 'coffee',
  salad: 'salad',
  steak: 'steak',
  beef: 'steak',
  banana: 'banana',
  chicken: 'chicken',
  pasta: 'pasta',
  spaghetti: 'pasta',
  noodles: 'pasta',
};

// Sample scan history data
export const SAMPLE_HISTORY = [
  { ...FOOD_DATABASE.pizza, timestamp: Date.now() - 3600000, scanId: 'scan-1' },
  { ...FOOD_DATABASE.apple, timestamp: Date.now() - 86400000, scanId: 'scan-2' },
  { ...FOOD_DATABASE.burger, timestamp: Date.now() - 172800000, scanId: 'scan-3' },
  { ...FOOD_DATABASE.coffee, timestamp: Date.now() - 259200000, scanId: 'scan-4' },
];
